name: Deploy MusicDiscovery App to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci


      - name: Remove old app.zip
        run: rm -rf app.zip

      - name: Archive project
        run: zip -r app.zip . -x "*.git*" "node_modules/*" ".github/*"

      - name: Code archive to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: "app.zip"
          target: "~"

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            set -e

            # Tentukan direktori proyek
            PROJECT_DIR="/home/${{ secrets.EC2_USER }}/music-discovery-backend"
            
            # Buat direktori jika belum ada
            mkdir -p $PROJECT_DIR

            # 1. FIX UTAMA: Ubah kepemilikan folder ke user yang sedang login
            # Ini akan menyelesaikan semua masalah 'Permission Denied'
            sudo chown -R ${{ secrets.EC2_USER }}:${{ secrets.EC2_USER }} $PROJECT_DIR

            # Pindah ke direktori proyek
            cd $PROJECT_DIR

            # 2. FIX LOGIKA: Ekstrak file zip di sini, menimpa file lama
            unzip -o "/home/${{ secrets.EC2_USER }}/app.zip"

            # Hapus file zip setelah diekstrak
            rm "/home/${{ secrets.EC2_USER }}/app.zip"

            # Buat file .env dari secrets
            cd ~
            rm -rf music-discovery-backend/
            sudo apt install -y unzip
            unzip -o app.zip -d music-discovery-backend
            cd music-discovery-backend
            cat <<EOF> .env
            JWT_SECRET_KEY= '${{ secrets.JWT_SECRET_KEY }}'
            GOOGLE_APP_PASSWORD= '${{ secrets.GOOGLE_APP_PASSWORD }}'
            GOOGLE_CLIENT_ID= '${{ secrets.GOOGLE_CLIENT_ID }}'
            GOOGLE_SECRET= '${{ secrets.GOOGLE_SECRET }}'
            AWS_ACCESS_KEY_ID= '${{ secrets.AWS_ACCESS_KEY_ID }}'
            AWS_SECRET_ACCESS_KEY= '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
            AWS_BUCKET_NAME= '${{ secrets.AWS_BUCKET_NAME }}'
            AWS_REGION= '${{ secrets.AWS_REGION }}'
            FRONTEND_URL='${{ secrets.FRONTEND_URL }}'
            BACKEND_URL='${{ secrets.BACKEND_URL }}'
            EOF
            
            # Install dependensi TANPA sudo, karena user sekarang memiliki folder
            npm install --production

            # Install/update PM2 secara global (ini butuh sudo)
            sudo npm install -g pm2

            # 4. FIX PM2: Gunakan 'restart' atau 'start' agar lebih aman
            # Ini akan me-restart aplikasi jika sudah berjalan, atau memulainya jika belum ada
            pm2 restart music-discovery-backend || pm2 start server.js --name music-discovery-backend
            sudo apt install -y nodejs npm
            sudo npm ci
            sudo npm i -g pm2
            pm2 delete all || true
            pm2 start server.js --name music-discovery-backend 
